### PR TITLE
fixes geo dash infinite loop

### LINKED ISSUE #962: addTileServer creates an infinite loop trying to reload the tile
The error function is continuously called if earth engine doesnt return a value.

### PR DESCRIPTION
**Pull request by rfontanarosa**
fix #962

### CODE REVIEW

File: src/js/geo-dash.js [hunk 1]
```diff
@@ -1076,9 +1076,9 @@ class MapWidget extends React.Component {
             source.on("tileloaderror", function(error) {
                 try {
                     window.setTimeout(function() {
-                        console.log("trying to reload the tile: " );
-                        console.log(error.tile);
-                        error.tile.load();
+                        error.tile.attempt = error.tile.attempt ? error.tile.attempt + 1 : 1;
+                        // console.log(`Trying to reload Tile ${error.tile.tileCoord.join("-")} (${error.tile.attempt}): `, error.tile);
```
Comment (sirmspencer) [inline src/js/geo-dash.js:1080]: Un comment or remove this line
